name: punish-gui
version: '${project.version}'
main: com.antho.punishgui.Punish_gui
api-version: '1.19'
commands:
  punish:
    permission: antho.punish
    permission-message: no.
  credits:
    description: by discord/anthony4933
permissions:
  antho.punish:
    default: false

author: discord/anthony4933
authors:
  - discord/anthony4933
  - github/anthony1204